import { FiArrowRight, FiBookOpen, FiCompass, FiMail, FiUsers } from "react-icons/fi";
import Navigation from "./Navigation";

const values = [
  { icon: FiBookOpen, title: "Access first", text: "Library resources should be simple to discover, regardless of a visitor’s technical experience." },
  { icon: FiUsers, title: "Built together", text: "We shape Libralink around the daily needs of students, librarians, and institutions." },
  { icon: FiCompass, title: "Purposeful technology", text: "Every feature should make finding, borrowing, and managing resources feel easier." },
];

function About() {
  return <div className="min-h-screen bg-[#F8FAFC]"><Navigation />
    <main>
      <section className="relative overflow-hidden bg-white px-4 pb-12 pt-24 sm:px-6 sm:pb-16 sm:pt-32 lg:px-8 lg:pb-24"><div className="absolute right-0 top-0 h-full w-1/2 opacity-[.06] [background:repeating-linear-gradient(90deg,#0077B6_0,#0077B6_18px,transparent_18px,transparent_28px)]" /><div className="relative mx-auto max-w-7xl"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#0077B6] sm:text-xs">About Libralink</p><div className="mt-3 grid gap-6 lg:grid-cols-[1.1fr_.9fr] lg:items-end sm:mt-4 sm:gap-8"><h1 className="max-w-3xl text-2xl font-semibold tracking-[-.04em] text-[#0F172A] sm:text-4xl lg:text-5xl">A simpler connection between people and knowledge.</h1><p className="max-w-xl text-sm leading-6 text-[#64748B] sm:text-base sm:leading-7">Libralink brings library discovery, borrowing, and connected-school access into one focused experience.</p></div></div></section>
      <section className="px-4 py-12 sm:px-6 sm:py-16 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1fr_.85fr] lg:items-center sm:gap-12"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#0077B6] sm:text-xs">Our purpose</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em] text-[#0F172A] sm:mt-3 sm:text-3xl lg:text-4xl">Make every shelf feel accessible.</h2><div className="mt-4 max-w-2xl space-y-4 text-sm leading-6 text-[#64748B] sm:mt-6 sm:text-base sm:leading-7"><p>Knowledge should not be hidden behind difficult catalogs or unfamiliar shelf systems. Libralink bridges the gap between digital search and the resources waiting in a real library.</p><p>By helping students discover titles and giving library teams a clearer workflow, the platform makes every library visit more useful.</p></div></div><aside className="border-l-4 border-[#0077B6] bg-white p-4 shadow-sm sm:p-6 lg:p-8"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#0077B6] sm:text-xs">Our promise</p><p className="mt-3 text-xl font-semibold leading-8 tracking-[-.02em] text-[#0F172A] sm:mt-4 sm:text-2xl sm:leading-9">A calm, reliable path from "Where is this book?" to "I found it."</p></aside></div></section>
      <section className="bg-white px-4 py-12 sm:px-6 sm:py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#0077B6] sm:text-xs">What guides us</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em] text-[#0F172A] sm:mt-3 sm:text-3xl lg:text-4xl">Designed for people who use libraries every day.</h2></div><div className="mt-8 grid gap-px overflow-hidden border border-slate-200 bg-slate-200 md:grid-cols-3 sm:mt-10">{values.map(({ icon: Icon, title, text }) => <article key={title} className="bg-white p-4 sm:p-6 lg:p-8"><Icon className="text-xl text-[#0077B6] sm:text-2xl" /><h3 className="mt-6 text-lg font-semibold sm:mt-8 sm:text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[#64748B] sm:mt-3">{text}</p></article>)}</div></div></section>
      <section className="bg-[#023E8A] px-4 py-12 text-white sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 md:flex-row md:items-end md:justify-between sm:gap-6"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#7DD3FC] sm:text-xs">Build a better library experience</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em] sm:mt-3 sm:text-3xl">Let's connect your library.</h2></div><a href="mailto:contact@libralink.com" className="inline-flex min-h-11 items-center justify-center gap-2 bg-white px-4 text-xs font-semibold text-[#023E8A] transition hover:bg-sky-50 sm:min-h-12 sm:px-5 sm:text-sm"><FiMail /> Contact our team <FiArrowRight /></a></div></section>
    </main>
  </div>;
}
export default About;
