import { useState } from "react";
import { FiClock, FiMail, FiMessageSquare, FiSend } from "react-icons/fi";
import Navigation from "./Navigation";

function Contact() {
  const [sent, setSent] = useState(false);
  const handleSubmit = (event) => { event.preventDefault(); setSent(true); };
  return <div className="min-h-screen bg-[#F8FAFC]"><Navigation /><main>
    <section className="bg-white px-4 pb-14 pt-32 sm:px-6 lg:px-8 lg:pb-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#0077B6]">Contact</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold tracking-[-.04em] text-[#0F172A] sm:text-5xl">A conversation starts with a question.</h1><p className="mt-5 max-w-xl leading-7 text-[#64748B]">For support, partnership discussions, or general inquiries, our team is here to help.</p></div></section>
    <section className="px-4 py-12 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><aside><h2 className="text-2xl font-semibold tracking-[-.02em]">Talk with Libralink</h2><p className="mt-3 leading-7 text-[#64748B]">Send us a message and we will direct it to the right team.</p><div className="mt-8 divide-y divide-slate-200 border-y border-slate-200"><a href="mailto:support@libralink.com" className="flex gap-4 py-5 transition hover:text-[#0077B6]"><FiMail className="mt-0.5 text-xl text-[#0077B6]" /><span><span className="block text-sm font-semibold text-[#0F172A]">Email support</span><span className="mt-1 block text-sm text-[#64748B]">support@libralink.com</span></span></a><div className="flex gap-4 py-5"><FiClock className="mt-0.5 text-xl text-[#0077B6]" /><span><span className="block text-sm font-semibold text-[#0F172A]">Response time</span><span className="mt-1 block text-sm text-[#64748B]">We aim to respond during library business hours.</span></span></div><div className="flex gap-4 py-5"><FiMessageSquare className="mt-0.5 text-xl text-[#0077B6]" /><span><span className="block text-sm font-semibold text-[#0F172A]">Partnerships</span><span className="mt-1 block text-sm text-[#64748B]">Tell us about your institution and library needs.</span></span></div></div></aside>
      <div className="border border-slate-200 bg-white p-5 shadow-sm sm:p-8"><h2 className="text-2xl font-semibold tracking-[-.02em]">Send a message</h2><p className="mt-2 text-sm text-[#64748B]">Fields marked required help us answer accurately.</p>{sent ? <div className="mt-7 border-l-4 border-[#16A34A] bg-green-50 p-5"><p className="font-semibold text-green-800">Message prepared</p><p className="mt-1 text-sm text-green-700">Please email support@libralink.com to send your inquiry directly to the team.</p><button type="button" onClick={() => setSent(false)} className="mt-4 text-sm font-semibold text-[#0077B6]">Write another message</button></div> : <form onSubmit={handleSubmit} className="mt-7 space-y-5"><div className="grid gap-5 sm:grid-cols-2"><Field id="name" label="Full name" placeholder="Your name" required /><Field id="email" label="Email address" type="email" placeholder="you@example.com" required /></div><Field id="subject" label="Subject" placeholder="How can we help?" required /><div><label htmlFor="message" className="mb-2 block text-sm font-medium">Message</label><textarea id="message" required rows="6" placeholder="Tell us more about your inquiry..." className="w-full resize-y border border-slate-200 bg-[#F8FAFC] px-3 py-3 text-base outline-none transition placeholder:text-slate-400 focus:border-[#0077B6] focus:ring-4 focus:ring-[#0077B6]/10 sm:text-sm" /></div><button type="submit" className="inline-flex min-h-12 w-full items-center justify-center gap-2 bg-[#0077B6] px-5 text-sm font-semibold text-white transition hover:bg-[#00669d]"><FiSend /> Send message</button></form>}</div></div></section>
  </main></div>;
}
function Field({ id, label, type = "text", placeholder, required = false }) { return <div><label htmlFor={id} className="mb-2 block text-sm font-medium">{label}</label><input id={id} type={type} placeholder={placeholder} required={required} className="min-h-12 w-full border border-slate-200 bg-[#F8FAFC] px-3 text-base outline-none transition placeholder:text-slate-400 focus:border-[#0077B6] focus:ring-4 focus:ring-[#0077B6]/10 sm:text-sm" /></div>; }
export default Contact;
