import { useState } from "react";
import { FiClock, FiMail, FiMessageSquare, FiSend } from "react-icons/fi";
import Navigation from "./Navigation";

function Contact() {
  const [sent, setSent] = useState(false);
  const handleSubmit = (event) => { event.preventDefault(); setSent(true); };
  return <div className="min-h-screen bg-[#F8FAFC]"><Navigation /><main>
    <section className="bg-white px-4 pb-10 pt-24 sm:px-6 sm:pb-14 sm:pt-32 lg:px-8 lg:pb-20"><div className="mx-auto max-w-7xl"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#0077B6] sm:text-xs">Contact</p><h1 className="mt-2 max-w-3xl text-2xl font-semibold tracking-[-.04em] text-[#0F172A] sm:mt-3 sm:text-4xl lg:text-5xl">A conversation starts with a question.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#64748B] sm:mt-5 sm:text-base sm:leading-7">For support, partnership discussions, or general inquiries, our team is here to help.</p></div></section>
    <section className="px-4 py-10 sm:px-6 sm:py-12 lg:px-8 lg:py-20"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.8fr_1.2fr] sm:gap-10"><aside><h2 className="text-xl font-semibold tracking-[-.02em] text-[#0F172A] sm:text-2xl">Talk with Libralink</h2><p className="mt-2 text-sm leading-6 text-[#64748B] sm:mt-3 sm:text-base sm:leading-7">Send us a message and we will direct it to the right team.</p><div className="mt-6 divide-y divide-slate-200 border-y border-slate-200 sm:mt-8"><a href="mailto:support@libralink.com" className="flex gap-3 py-4 transition hover:text-[#0077B6] sm:gap-4 sm:py-5"><FiMail className="mt-0.5 text-lg text-[#0077B6] sm:text-xl" /><span><span className="block text-sm font-semibold text-[#0F172A]">Email support</span><span className="mt-1 block text-sm text-[#64748B]">support@libralink.com</span></span></a><div className="flex gap-3 py-4 sm:gap-4 sm:py-5"><FiClock className="mt-0.5 text-lg text-[#0077B6] sm:text-xl" /><span><span className="block text-sm font-semibold text-[#0F172A]">Response time</span><span className="mt-1 block text-sm text-[#64748B]">We aim to respond during library business hours.</span></span></div><div className="flex gap-3 py-4 sm:gap-4 sm:py-5"><FiMessageSquare className="mt-0.5 text-lg text-[#0077B6] sm:text-xl" /><span><span className="block text-sm font-semibold text-[#0F172A]">Partnerships</span><span className="mt-1 block text-sm text-[#64748B]">Tell us about your institution and library needs.</span></span></div></div></aside>
      <div className="border border-slate-200 bg-white p-4 shadow-sm sm:p-5 lg:p-8"><h2 className="text-xl font-semibold tracking-[-.02em] text-[#0F172A] sm:text-2xl">Send a message</h2><p className="mt-2 text-sm text-[#64748B]">Fields marked required help us answer accurately.</p>{sent ? <div className="mt-5 border-l-4 border-[#16A34A] bg-green-50 p-4 sm:mt-7 sm:p-5"><p className="font-semibold text-green-800">Message prepared</p><p className="mt-1 text-sm text-green-700">Please email support@libralink.com to send your inquiry directly to the team.</p><button type="button" onClick={() => setSent(false)} className="mt-3 text-sm font-semibold text-[#0077B6] sm:mt-4">Write another message</button></div> : <form onSubmit={handleSubmit} className="mt-5 space-y-4 sm:mt-7 sm:space-y-5"><div className="grid gap-4 sm:grid-cols-2 sm:gap-5"><Field id="name" label="Full name" placeholder="Your name" required /><Field id="email" label="Email address" type="email" placeholder="you@example.com" required /></div><Field id="subject" label="Subject" placeholder="How can we help?" required /><div><label htmlFor="message" className="mb-2 block text-sm font-medium">Message</label><textarea id="message" required rows="5" placeholder="Tell us more about your inquiry..." className="w-full resize-y border border-slate-200 bg-[#F8FAFC] px-3 py-3 text-sm outline-none transition placeholder:text-slate-400 focus:border-[#0077B6] focus:ring-4 focus:ring-[#0077B6]/10 sm:rows-6 sm:text-base" /></div><button type="submit" className="inline-flex min-h-11 w-full items-center justify-center gap-2 bg-[#0077B6] px-4 text-xs font-semibold text-white transition hover:bg-[#00669d] sm:min-h-12 sm:px-5 sm:text-sm"><FiSend /> Send message</button></form>}</div></div></section>
  </main></div>;
}
function Field({ id, label, type = "text", placeholder, required = false }) { return <div><label htmlFor={id} className="mb-2 block text-sm font-medium">{label}</label><input id={id} type={type} placeholder={placeholder} required={required} className="min-h-11 w-full border border-slate-200 bg-[#F8FAFC] px-3 text-sm outline-none transition placeholder:text-slate-400 focus:border-[#0077B6] focus:ring-4 focus:ring-[#0077B6]/10 sm:min-h-12 sm:text-base" /></div>; }
export default Contact;
